apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-config
data:
  config.yaml: |
    model:
      default: gemini-3.1-flash-lite-preview
      provider: custom
      base_url: http://litellm-service:4000/v1
      api_key: sk-litellm-proxy-secret
---
apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: hermes-sandbox-gvisor
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: hermes-sandbox-gvisor
    spec:
      runtimeClassName: gvisor
      automountServiceAccountToken: false
      # 在 Pod 级别统一设置权限上下文
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-config
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args: ["cp /tmp/config.yaml /opt/data/config.yaml && chown 1000:1000 /opt/data/config.yaml"]
          volumeMounts:
            - name: hermes-pvc
              mountPath: /opt/data
            - name: config
              mountPath: /tmp/config.yaml
              subPath: config.yaml
      containers:
        - name: hermes
          image: us-central1-docker.pkg.dev/flius-test-15/dockerhub/nousresearch/hermes-agent
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["sleep infinity"]
          volumeMounts:
            - name: hermes-pvc
              mountPath: /opt/data
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: config
          configMap:
            name: hermes-config
  volumeClaimTemplates:
    - metadata:
        name: hermes-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi