apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
data:
  openclaw.json: |
    {
      "gateway": {
        "controlUi": {
          "dangerouslyAllowHostHeaderOriginFallback": true
        }
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspaces-pvc-shared
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  name: openclaw-template-kata
  namespace: default
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: openclaw-sandbox
    spec:
      runtimeClassName: kata-clh
      containers:
        # 主容器：OpenClaw
        - name: openclaw
          image: ghcr.io/openclaw/openclaw:2026.3.23
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          env:
            - name: OPENCLAW_GATEWAY_TOKEN
              value: "dummy-token-for-sandbox"
            - name: OPENCLAW_CONFIG_PATH
              value: "/etc/openclaw/openclaw.json"
          command:
            - node
            - dist/index.js
            - gateway
            - --bind=lan
            - --port
            - "18789"
            - --allow-unconfigured
            - --verbose
          volumeMounts:
            - mountPath: /home/node/.openclaw/workspace
              name: workspaces-storage
            - mountPath: /etc/openclaw
              name: cm-volume
      
      volumes:
        - name: workspaces-storage
          persistentVolumeClaim:
            claimName: workspaces-pvc-shared
        - name: cm-volume
          configMap:
            name: openclaw-config
---
apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: openclaw-warmpool-kata
  namespace: default
spec:
  replicas: 1
  sandboxTemplateRef:
    name: openclaw-template-kata
